services:
  ring_a:  # _ring_scale_unit suffix
    image: sdp-app:a
    ports:
      - "7911-7913:${APP_PORT}"
    deploy:
      mode: replicated
      replicas: 3
    healthcheck: &healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}/health"]
      interval: 1s
      timeout: 10s  # for curl
      retries: 0
      start_period: 5s  # for Flask
  ring_b:
    image: sdp-app:b
    ports:
      - "7921-7923:${APP_PORT}"
    deploy:
      mode: replicated
      replicas: 3
    healthcheck: *healthcheck
  ring_c:
    image: sdp-app:c
    ports:
      - "7931-7933:${APP_PORT}"
    deploy:
      mode: replicated
      replicas: 3
    healthcheck: *healthcheck
  failover_a:
    image: nginx-custom:latest
    build: &nginx_build
      context: ./nginx
      dockerfile: Dockerfile
    network_mode: host
    environment:
        PORT: "7910"
        FAILOVER_PORT_1: "7911"
        FAILOVER_PORT_2: "7912"
        FAILOVER_PORT_3: "7913"
  failover_b:
    image: nginx-custom:latest
    build: *nginx_build
    network_mode: host
    environment:
        PORT: "7920"
        FAILOVER_PORT_1: "7921"
        FAILOVER_PORT_2: "7922"
        FAILOVER_PORT_3: "7923"
  failover_c:
    image: nginx-custom:latest
    build: *nginx_build
    network_mode: host
    environment:
        PORT: "7930"
        FAILOVER_PORT_1: "7931"
        FAILOVER_PORT_2: "7932"
        FAILOVER_PORT_3: "7933"
